// Generated by https://pagedraw.io/pages/8417
import React from 'react';
import './_submittableinput.css';

function render() {
    return <div className="_submittableinput-_submittableinput-2">
        <div className="_submittableinput-0">
            <div className="_submittableinput-0-0">
                <div className="_submittableinput-0-0-0">
                    <div className="_submittableinput-path-1">
                        <div className="_submittableinput-0-0-0-0-0">
                            <div className="_submittableinput-0-0-0-0-0-0">
                                <input type="text" placeholder="Your comment" value={this.props.value} onChange={this.props.onChange} onKeyDown={this.props.onKeyDown} className="_submittableinput-text_input-5" /> 
                            </div>
                        </div>
                    </div>
                </div>
                <div className="_submittableinput-0-0-1">
                    <div className="_submittableinput-path-10" /> 
                </div>
            </div>
            <div className="_submittableinput-0-1">
                <div className="_submittableinput-0-1-0">
                    <div onClick={this.props.onClick} className="_submittableinput-oval-1">
                        <div className="_submittableinput-0-1-0-0-0">
                            <div className="_submittableinput-_-9">{"+"}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}