// Generated by https://pagedraw.io/4872
import Rating from './rating';
import React from 'react';
import './artboard.css';
function render() {
    return <div className="artboard">
        <div className="artboard-0">
            <div className="artboard-artboard-8">
                <div className="artboard-0-0-0">
                    <div className="artboard-rectangle-4">
                        <div className="artboard-0-0-0-0-0">
                            <div className="artboard-movie_reviews_-9">
                                { this.props.title }
                            </div>
                        </div>
                        <div className="artboard-0-0-0-0-1">
                            <img src={this.props.img_src} onClick={this.props.changeMovie} className="artboard-image-0" /> 
                        </div>
                        <div className="artboard-0-0-0-0-2">
                            <div className="artboard-rating-7">
                                <Rating rating={this.props.rating} setRating={this.props.setRating} /> 
                            </div>
                        </div>
                        <div className="artboard-0-0-0-0-3">
                            <div className="artboard-0-0-0-0-3-0">
                                { this.props.reviews.map((review, i) => {
                                    return <div key={i} className="artboard-rectangle_2">
                                        <div className="artboard-0-0-0-0-3-0-0-0-0">
                                            <div className="artboard-this_has_to_be_the_best_movie_ever_-4">
                                                { review.content }
                                            </div>
                                        </div>
                                        <div className="artboard-0-0-0-0-3-0-0-0-1">
                                            <div className="artboard-rectangle_3" /> 
                                        </div>
                                    </div>;
                                }) }
                            </div>
                        </div>
                        <div className="artboard-0-0-0-0-4">
                            <input type="text" placeholder="Your comment here" value={this.props.commentBeingTyped} onSubmit={this.props.addComment} onChange={this.props.onChangeComment} className="artboard-text_input-4" /> 
                        </div>
                        <div className="artboard-0-0-0-0-5">
                            <button type="submit" onClick={this.props.addComment} className="artboard-add_comment-5">
                                <span>Add comment</span>
                            </button>
                        </div>
                    </div>
                </div>
                <div className="artboard-0-0-1" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}