// Generated by https://pagedraw.io/pages/4872
import Multistate_group from './multistate_group';
import React from 'react';
import './desktop_hd.css';

function render() {
    return <div className="desktop_hd">
        <div className="desktop_hd-0">
            <div className="desktop_hd-desktop_hd-1">
                <div className="desktop_hd-0-0-0">
                    <div className="desktop_hd-path-7">
                        <div className="desktop_hd-0-0-0-0-0">
                            <div className="desktop_hd-0-0-0-0-0-0">
                                <div className="desktop_hd-0-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6898767722384136-1511160906340-99F634CE-B11B-4E2B-89EA-235A929412DB.png" className="desktop_hd-local_movies_-_material-6" /> 
                                </div>
                            </div>
                            <div className="desktop_hd-movietime-1">Movietime</div>
                        </div>
                        <div className="desktop_hd-0-0-0-0-1">
                            <div className="desktop_hd-browse-1">BROWSE</div>
                        </div>
                        <div className="desktop_hd-0-0-0-0-2">
                            <div className="desktop_hd-path-9">
                                <div className="desktop_hd-0-0-0-0-2-0-0">
                                    <div className="desktop_hd-path-1" /> 
                                    <div className="desktop_hd-0-0-0-0-2-0-0-1">
                                        <div className="desktop_hd-0-0-0-0-2-0-0-1-0">
                                            <div className="desktop_hd-popular-1">POPULAR</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="desktop_hd-0-0-0-0-3">
                            <div className="desktop_hd-new-1">NEW</div>
                        </div>
                        <div className="desktop_hd-0-0-0-0-4" /> 
                    </div>
                    <div className="desktop_hd-0-0-0-1">
                        <div className="desktop_hd-0-0-0-1-0">
                            <div className="desktop_hd-0-0-0-1-0-0">
                                <div className="desktop_hd-0-0-0-1-0-0-0">
                                    <div className="desktop_hd-pulp_fiction-8">
                                        { this.props.title }
                                    </div>
                                </div>
                                <div className="desktop_hd-0-0-0-1-0-0-1">
                                    <div className="desktop_hd-1">
                                        { this.props.movie_year }
                                    </div>
                                    <div className="desktop_hd-0-0-0-1-0-0-1-1" /> 
                                </div>
                                <div className="desktop_hd-0-0-0-1-0-0-2">
                                    <div className="desktop_hd-path-3" /> 
                                </div>
                                <div className="desktop_hd-0-0-0-1-0-0-3">
                                    <div className="desktop_hd-the_lives_of_two_mob-1">
                                        { this.props.movie_description }
                                    </div>
                                </div>
                                <div className="desktop_hd-0-0-0-1-0-0-4">
                                    <div className="desktop_hd-director_-5">Director:</div>
                                    <div className="desktop_hd-quentin_tarantino-1">
                                        { this.props.director }
                                    </div>
                                </div>
                            </div>
                            <div onClick={this.props.changeMovie} className="desktop_hd-img-1" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
                        </div>
                        <div className="desktop_hd-0-0-0-1-1">
                            <div className="desktop_hd-rectangle_2">
                                <div className="desktop_hd-0-0-0-1-1-0-0">
                                    <div className="desktop_hd-write_a_comment-9">
                                        Write a comment
                                    </div>
                                    <div className="desktop_hd-what_did_you_think_-1">
                                        What did you think?
                                    </div>
                                </div>
                                <div className="desktop_hd-0-0-0-1-1-0-1">
                                    <div className="desktop_hd-path-36">
                                        <div className="desktop_hd-0-0-0-1-1-0-1-0-0">
                                            <div className="desktop_hd-0-0-0-1-1-0-1-0-0-0">
                                                { this.props.reviews.map((item, i) => {
                                                    return <div key={i} className="desktop_hd-rectangle-2">
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-0-0-0-0-0-0">
                                                            <div className="desktop_hd-i_posted_a_comment_a-1">
                                                                { item.content }
                                                            </div>
                                                        </div>
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-0-0-0-0-0-1">
                                                            <div className="desktop_hd-path-15" /> 
                                                        </div>
                                                    </div>;
                                                }) }
                                            </div>
                                        </div>
                                        <div className="desktop_hd-0-0-0-1-1-0-1-0-1">
                                            <div className="desktop_hd-0-0-0-1-1-0-1-0-1-0">
                                                <div className="desktop_hd-0-0-0-1-1-0-1-0-1-0-0">
                                                    <div className="desktop_hd-path-16">
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-0-1-0-0-0-0">
                                                            <input type="text" placeholder="Your comment" value={this.props.commentBeingTyped} onChange={this.props.onChangeComment} className="desktop_hd-text_input-3" /> 
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="desktop_hd-0-0-0-1-1-0-1-0-1-0-1">
                                                    <div className="desktop_hd-path-10" /> 
                                                </div>
                                            </div>
                                            <div className="desktop_hd-0-0-0-1-1-0-1-0-1-1">
                                                <div className="desktop_hd-0-0-0-1-1-0-1-0-1-1-0">
                                                    <div onClick={this.props.addComment} className="desktop_hd-oval-1">
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-0-1-1-0-0-0">
                                                            <div className="desktop_hd-_-9">+</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="desktop_hd-0-0-0-1-1-0-1-1">
                                        <div className="desktop_hd-0-0-0-1-1-0-1-1-0">
                                            <div className="desktop_hd-path-17">
                                                <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0">
                                                    <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-0">
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-0-0">
                                                            <div onClick={() => this.props.setRating(1)} className="desktop_hd-multistate_group_instance-1">
                                                                <Multistate_group state={(this.props.rating > 0 ? 'default' : 'state_1')} /> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-1">
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-1-0">
                                                            <div onClick={() => this.props.setRating(2)} className="desktop_hd-multistate_group_instance-7">
                                                                <Multistate_group state={(this.props.rating > 1 ? 'default' : 'state_1')} /> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-2">
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-2-0">
                                                            <div onClick={() => this.props.setRating(3)} className="desktop_hd-multistate_group_instance_2">
                                                                <Multistate_group state={(this.props.rating > 2 ? 'default' : 'state_1')} /> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-3">
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-3-0">
                                                            <div onClick={() => this.props.setRating(4)} className="desktop_hd-multistate_group_instance_3">
                                                                <Multistate_group state={(this.props.rating > 3 ? 'default' : 'state_1')} /> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-4">
                                                        <div className="desktop_hd-0-0-0-1-1-0-1-1-0-0-0-4-0">
                                                            <div onClick={() => this.props.setRating(5)} className="desktop_hd-multistate_group_instance_2-3">
                                                                <Multistate_group state={(this.props.rating > 4 ? 'default' : 'state_1')} /> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}