// Generated by https://pagedraw.io/pages/4872
import Tab from './tab';
import Submittableinput from './submittableinput';
import Rating from './rating';
import React from 'react';
import './desktop_hd.css';

function render() {
    return <div className="desktop_hd-desktop_hd-1">
        <div className="desktop_hd-0">
            <div className="desktop_hd-path-7">
                <div className="desktop_hd-0-0-0">
                    <div className="desktop_hd-0-0-0-0">
                        <div className="desktop_hd-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6898767722384136-1511193194356-99F634CE-B11B-4E2B-89EA-235A929412DB.png" className="desktop_hd-local_movies_-_material-6" /> 
                        </div>
                    </div>
                    <div className="desktop_hd-movietime-1">Movietime</div>
                </div>
                <div className="desktop_hd-0-0-1">
                    <div className="desktop_hd-multistate_group_instance_4">
                        <Tab state={"default"} text={"BROWSE"} /> 
                    </div>
                </div>
                <div className="desktop_hd-0-0-2">
                    <div className="desktop_hd-multistate_group_instance_5">
                        <Tab state={"selected"} text={"POPULAR"} /> 
                    </div>
                </div>
                <div className="desktop_hd-0-0-3">
                    <div className="desktop_hd-tab-2">
                        <Tab state={"default"} text={"NEW"} /> 
                    </div>
                </div>
                <div className="desktop_hd-0-0-4" /> 
            </div>
            <div className="desktop_hd-0-1">
                <div className="desktop_hd-0-1-0">
                    <div className="desktop_hd-pulp_fiction-8">
                        { this.props.movie_title }
                    </div>
                </div>
                <div className="desktop_hd-0-1-1">
                    <div className="desktop_hd-1">
                        { this.props.movie_year }
                    </div>
                    <div className="desktop_hd-0-1-1-1" /> 
                </div>
                <div className="desktop_hd-0-1-2">
                    <div className="desktop_hd-path-3" /> 
                </div>
                <div className="desktop_hd-0-1-3">
                    <div className="desktop_hd-the_lives_of_two_mob-1">
                        { this.props.movie_description }
                    </div>
                </div>
                <div className="desktop_hd-0-1-4">
                    <div className="desktop_hd-director_-5">{"Director:"}</div>
                    <div className="desktop_hd-quentin_tarantino-1">
                        { this.props.director }
                    </div>
                </div>
                <div className="desktop_hd-0-1-5">
                    <div className="desktop_hd-write_a_comment-9">
                        Write a comment
                    </div>
                </div>
                <div className="desktop_hd-0-1-6">
                    <div className="desktop_hd-path-36">
                        <div className="desktop_hd-0-1-6-0-0">
                            <div className="desktop_hd-0-1-6-0-0-0">
                                { this.props.reviews.map((item, i) => {
                                    return <div key={i} className="desktop_hd-rectangle-3">
                                        <div className="desktop_hd-0-1-6-0-0-0-0-0-0">
                                            <div className="desktop_hd-i_posted_a_comment_a-1">
                                                { item.content }
                                            </div>
                                        </div>
                                        <div className="desktop_hd-0-1-6-0-0-0-0-0-1">
                                            <div className="desktop_hd-path-1" /> 
                                        </div>
                                    </div>;
                                }) }
                            </div>
                        </div>
                        <div className="desktop_hd-0-1-6-0-1">
                            <div className="desktop_hd-submittableinput-1">
                                <Submittableinput onSubmit={this.props.onAddComment} /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="desktop_hd-0-2">
                <div className="desktop_hd-0-2-0">
                    <div onClick={this.props.onChangeMovie} className="desktop_hd-img-1" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
                </div>
                <div className="desktop_hd-0-2-1">
                    <div className="desktop_hd-what_did_you_think_-1">
                        {"What did you think?"}
                    </div>
                </div>
                <div className="desktop_hd-0-2-2">
                    <div className="desktop_hd-path-17">
                        <div className="desktop_hd-0-2-2-0-0">
                            <div className="desktop_hd-0-2-2-0-0-0" /> 
                            <div className="desktop_hd-component_1">
                                <Rating rating={this.props.rating} setRating={this.props.setRating} /> 
                            </div>
                            <div className="desktop_hd-0-2-2-0-0-2" /> 
                        </div>
                    </div>
                </div>
                <div className="desktop_hd-0-2-3" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}