// Generated by https://pagedraw.io/pages/8417
import Tab from './tab';
import Submittableinput from './submittableinput';
import Rating from './rating';
import React from 'react';
import './mainscreen.css';

function render() {
    return <div className="mainscreen-mainscreen-8">
        <div className="mainscreen-0">
            <div className="mainscreen-path-2">
                <div className="mainscreen-0-0-0">
                    <div className="mainscreen-0-0-0-0">
                        <div className="mainscreen-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8126710621713976-1521066391954-63A58C9A-313A-4281-ADCB-6CF402BC5A7F.png" className="mainscreen-local_movies_-_material-2" /> 
                        </div>
                    </div>
                    <div className="mainscreen-movietime-5">Movietime</div>
                </div>
                <div className="mainscreen-0-0-1">
                    <div className="mainscreen-tab-2">
                        <Tab state={"default"} text={"NEW"} /> 
                    </div>
                </div>
                <div className="mainscreen-0-0-2">
                    <div className="mainscreen-tab-6">
                        <Tab state={"selected"} text={"POPULAR"} /> 
                    </div>
                </div>
                <div className="mainscreen-0-0-3">
                    <div className="mainscreen-tab-8">
                        <Tab state={"default"} text={"BROWSE"} /> 
                    </div>
                </div>
                <div className="mainscreen-0-0-4" /> 
            </div>
            <div className="mainscreen-0-1">
                <div className="mainscreen-0-1-0">
                    <div className="mainscreen-the_lion_king-1">
                        { this.props.movie_title }
                    </div>
                </div>
                <div className="mainscreen-0-1-1">
                    <div className="mainscreen-1">
                        { this.props.movie_year }
                    </div>
                    <div className="mainscreen-0-1-1-1" /> 
                </div>
                <div className="mainscreen-0-1-2">
                    <div className="mainscreen-path-3" /> 
                </div>
                <div className="mainscreen-0-1-3">
                    <div className="mainscreen-a_lion_cub_crown_pri-9">
                        { this.props.movie_description }
                    </div>
                </div>
                <div className="mainscreen-0-1-4">
                    <div className="mainscreen-directors_-5">
                        {"Directors:"}
                    </div>
                    <div className="mainscreen-roger_allers_rob_mi-2">
                        { this.props.director }
                    </div>
                </div>
                <div className="mainscreen-0-1-5">
                    <div className="mainscreen-write_a_comment-8">
                        Write a comment
                    </div>
                </div>
                <div className="mainscreen-0-1-6">
                    <div className="mainscreen-path-23">
                        <div className="mainscreen-0-1-6-0-0">
                            <div className="mainscreen-0-1-6-0-0-0">
                                { this.props.reviews.map((elem, i) => {
                                    return <div key={i} className="mainscreen-rectangle-6">
                                        <div className="mainscreen-0-1-6-0-0-0-0-0-0">
                                            <div className="mainscreen-i_posted_a_comment_a-2">
                                                { elem.content }
                                            </div>
                                        </div>
                                        <div className="mainscreen-0-1-6-0-0-0-0-0-1">
                                            <div className="mainscreen-path-34" /> 
                                        </div>
                                    </div>;
                                }) }
                            </div>
                        </div>
                        <div className="mainscreen-0-1-6-0-1">
                            <div className="mainscreen-submittableinput-0">
                                <Submittableinput onSubmit={this.props.onAddComment} /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="mainscreen-0-2">
                <div className="mainscreen-0-2-0">
                    <div className="mainscreen-bitmap-3" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
                </div>
                <div className="mainscreen-0-2-1">
                    <div className="mainscreen-what_did_you_think_-8">
                        {"What did you think?"}
                    </div>
                </div>
                <div className="mainscreen-0-2-2">
                    <div className="mainscreen-path-0">
                        <div className="mainscreen-0-2-2-0-0">
                            <div className="mainscreen-0-2-2-0-0-0" /> 
                            <div className="mainscreen-rating-8">
                                <Rating rating={this.props.rating} setRating={this.props.setRating} /> 
                            </div>
                            <div className="mainscreen-0-2-2-0-0-2" /> 
                        </div>
                    </div>
                </div>
                <div className="mainscreen-0-2-3" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}