// Generated by https://pagedraw.io/pages/4872
import React from 'react';
import './multistate_group.css';

function render() {
    return <div className="pd-onhover-parent multistate_group">
        { (this.props.state == "default") ?
            <div className="multistate_group-0-0">
                <div className="multistate_group-0-0-0">
                    <div className="multistate_group-default-4">
                        <div className="multistate_group-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1665832666386382-1511160906399-398E6BDC-9BD7-493F-A38C-0607C0EE0925.png" className="multistate_group-star_d-1" /> 
                        </div>
                        <div className="multistate_group-0-0-0-0-1" /> 
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state == "state_1") ?
            <div className="multistate_group-1-0">
                <div className="multistate_group-1-0-0">
                    <div className="multistate_group-state_1">
                        <div className="multistate_group-1-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8597227200794478-1511160906609-3EBBFA9A-B2B0-4A32-BE2B-14F4394BAAF9.png" className="multistate_group-star_d-8" /> 
                        </div>
                        <div className="multistate_group-1-0-0-0-1" /> 
                    </div>
                </div>
            </div>
        : null}
        <div className="pd-onhover multistate_group-2">
            <div className="multistate_group-2-0">
                <div className="multistate_group-state_2">
                    <div className="multistate_group-2-0-0-0">
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2502252748025969-1511160906549-083433D1-8743-4914-B9B6-4BB3D21CD383.png" className="multistate_group-star_d-2" /> 
                    </div>
                    <div className="multistate_group-2-0-0-1" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}