// Generated by https://pagedraw.io/pages/4872
import React from 'react';
import './star.css';

function render() {
    return <div className="pd-onhover-parent star">
        { (this.props.state === "state_1") ?
            <div className="star-state_1">
                <div className="star-0-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8597227200794478-1511193194717-3EBBFA9A-B2B0-4A32-BE2B-14F4394BAAF9.png" className="star-star_d-8" /> 
                </div>
                <div className="star-0-0-1" /> 
            </div>
        : null}
        <div className="pd-onhover star-state_2">
            <div className="star-1-0">
                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2502252748025969-1511193194815-083433D1-8743-4914-B9B6-4BB3D21CD383.png" className="star-star_d-2" /> 
            </div>
            <div className="star-1-1" /> 
        </div>
        { (this.props.state === "default") ?
            <div className="star-default-6">
                <div className="star-2-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1665832666386382-1511193194749-398E6BDC-9BD7-493F-A38C-0607C0EE0925.png" className="star-star_d-1" /> 
                </div>
                <div className="star-2-0-1" /> 
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}