// Generated by https://pagedraw.io/pages/4872
import SubmittableInputWrapper from '../submittable-input-wrapper';
import _submittableinput from './_submittableinput';
import React from 'react';
import './submittableinput.css';

function render() {
    return <div className="submittableinput-submittableinput-7">
        <SubmittableInputWrapper onSubmit={this.props.onSubmit} />
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}