// Generated by https://pagedraw.io/pages/8417
import React from 'react';
import './tab.css';

function render() {
    return <div className="tab">
        { (this.props.state === "selected") ?
            <div className="tab-selected-9">
                <div className="tab-0-0-0">
                    <div className="tab-path-9">
                        <div className="tab-0-0-0-0-0">
                            <div className="tab-path-1" /> 
                            <div className="tab-0-0-0-0-0-1">
                                <div className="tab-0-0-0-0-0-1-0">
                                    <div className="tab-popular-1">{ this.props.text }</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
        { (this.props.state === "default") ?
            <div className="tab-default-9">
                <div className="tab-1-0-0">
                    <div className="tab-rectangle_3">
                        <div className="tab-1-0-0-0-0">
                            <div onClick={() => window.alert('Not implemented')} className="tab-browse-1">
                                { this.props.text }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        : null}
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}